import { useEffect, useMemo, useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { ArrowUpRight, ChevronLeft, ChevronRight, Menu, Search, Star, X } from "lucide-react";

const IMG = {
  hero: "https://framerusercontent.com/images/g813yVl0fq2gEobS7kOZx537SY.jpg?width=1408&height=1408",
  urban: "https://framerusercontent.com/images/Or4CSjqekPU2Ug6V0zSDTbgtg.jpg?width=1734&height=1564",
  latest: "https://framerusercontent.com/images/YI6OX1Ix0QFPJHufS272fscYaI.jpg?width=1060&height=1074",
  premium: "https://framerusercontent.com/images/HaLbFMQL3UBYnLDE5V1KjUjLbU.jpg?width=1584&height=1530",
  arctic: "https://framerusercontent.com/images/UqbagK5Zf6G91yyijIvdScOQDI.png?width=1555&height=1692",
  casual: "https://framerusercontent.com/images/7dwU69CcPP5QPRAcGcQvWaJXm3c.png?width=1264&height=1578",
  iconic: "https://framerusercontent.com/images/xXRw7s77WdhR0P4zOTGGkDW2qs.jpg?width=1840&height=1934",
  knit: "https://framerusercontent.com/images/lvt1WlyrgirePb8z3BSlF9OY.jpg?width=1920&height=2879",
  knitAlt: "https://framerusercontent.com/images/dfydRQ0hineaQjqYigxtJ3UUI.jpg?width=1920&height=2879",
  trench: "https://framerusercontent.com/images/eY6Dmvy1WrbgKmBxjcRhwuXCs.jpg?width=1920&height=2879",
  overalls: "https://framerusercontent.com/images/XKBImpA6SUFBTNUtQrmzAkMmj0.jpg?width=1920&height=2879",
  shirt: "https://framerusercontent.com/images/kanGnrYimBokWcnvmRshQIhToM.jpg?width=1920&height=2879",
  tee: "https://framerusercontent.com/images/m7vGnEDcM9ENme6wUOVRTjDCo.jpg?width=1920&height=2879",
  cargo: "https://framerusercontent.com/images/srFy8sCNq5IkDCNHign0ZVGFg.jpg?width=1920&height=2879",
};

type Product = { slug: string; name: string; price: string; old: string; tag?: string; image: string; alt?: string };
const products: Product[] = [
  { slug: "textured-knitted-shirt", name: "Textured Knitted Shirt", price: "$59.00", old: "$79.00", tag: "New", image: IMG.knit, alt: IMG.knitAlt },
  { slug: "structured-trench-coat", name: "Structured Trench Coat", price: "$210.00", old: "$280.00", tag: "New", image: IMG.trench, alt: IMG.knitAlt },
  { slug: "mini-denim-overalls", name: "Mini Denim Overalls", price: "$45.00", old: "$60.00", tag: "New", image: IMG.overalls, alt: IMG.knit },
  { slug: "riviera-collar-shirt", name: "Riviera Collar Shirt", price: "$45.00", old: "$60.00", tag: "New", image: IMG.shirt, alt: IMG.overalls },
  { slug: "stretch-jersey-tee", name: "Stretch Jersey Tee", price: "$65.00", old: "$95.00", tag: "New", image: IMG.tee, alt: IMG.shirt },
  { slug: "urban-utility-cargo", name: "Urban Utility Cargo", price: "$90.00", old: "$120.00", tag: "New", image: IMG.cargo, alt: IMG.tee },
  { slug: "classic-boxy-tee", name: "Classic Boxy Tee", price: "$35.00", old: "$45.00", tag: "New", image: IMG.tee, alt: IMG.knit },
  { slug: "pleated-smart-trousers", name: "Pleated Smart Trousers", price: "$76.00", old: "$100.00", tag: "New", image: IMG.cargo, alt: IMG.trench },
  { slug: "french-terry-shorts", name: "French Terry Shorts", price: "$40.00", old: "$55.00", tag: "New", image: IMG.overalls, alt: IMG.cargo },
  { slug: "heavyweight-oversized-hoodie", name: "Heavyweight Oversized Hoodie", price: "$85.00", old: "$110.00", tag: "Best seller", image: IMG.casual, alt: IMG.knit },
  { slug: "patterned-knit-sweater", name: "Patterned Knit Sweater", price: "$45.00", old: "$90.00", tag: "Best seller", image: IMG.premium, alt: IMG.knit },
  { slug: "quilted-bomber-jacket", name: "Quilted Bomber Jacket", price: "$145.00", old: "$180.00", tag: "Best seller", image: IMG.urban, alt: IMG.trench },
  { slug: "hooded-puffer-vest", name: "Hooded Puffer Vest", price: "$45.00", old: "$75.00", tag: "Best seller", image: IMG.arctic, alt: IMG.casual },
  { slug: "vegan-leather-leggings", name: "Vegan Leather Leggings", price: "$75.00", old: "$99.00", tag: "Best seller", image: IMG.latest, alt: IMG.urban },
  { slug: "cropped-boxy-blazer", name: "Cropped Boxy Blazer", price: "$130.00", old: "$175.00", tag: "Best seller", image: IMG.urban, alt: IMG.latest },
];
const blogs = [
  { slug: "how-to-master-the-art-of-minimal-street-style", category: "Style Guide", title: "How to master the art of minimal street style", excerpt: "Build a timeless, comfortable wardrobe with high-quality fabrics, muted tones, and effortless oversized fits.", time: "8 min read", date: "Jan 29, 2026", image: IMG.latest },
  { slug: "elevate-everyday-outfits-using-modern-minimalist-styling", category: "Fashion Tips", title: "Elevate everyday outfits using modern minimalist styling", excerpt: "", time: "8 min read", date: "12/30/25", image: IMG.urban },
  { slug: "build-a-capsule-wardrobe-that-works-year-round", category: "Style Guide", title: "Build a capsule wardrobe that works year round", excerpt: "", time: "5 min read", date: "11/22/25", image: IMG.premium },
];

function useReveal() {
  useEffect(() => {
    const els = document.querySelectorAll<HTMLElement>("[data-reveal]");
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("is-visible")), { threshold: 0.08 });
    els.forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);
}

function Header() {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 24); window.addEventListener("scroll", fn); return () => window.removeEventListener("scroll", fn); }, []);
  return <>
    <div className="announcement">Black friday sale 50% off <span>Black friday sale 50% off</span><span>Black friday sale 50% off</span><span>Black friday sale 50% off</span></div>
    <header className={`site-header ${scrolled ? "scrolled" : ""}`}>
      <Link href="/" className="wordmark">WEARIX</Link>
      <nav className="desktop-nav"><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/shop">Shop</Link><Link href="/blog">Blog</Link><Link href="/contact">Contact</Link></nav>
      <div className="header-actions"><button aria-label="Search" className="icon-button"><Search size={16}/></button><Link href="/shop" className="pill pill-light">Shop all items <ArrowUpRight size={15}/></Link><button aria-label="Open menu" className="menu-button" onClick={() => setOpen(true)}><Menu size={20}/></button></div>
    </header>
    {open && <div className="mobile-menu"><button className="close-menu" onClick={() => setOpen(false)}><X/></button><Link href="/" onClick={() => setOpen(false)}>Home</Link><Link href="/about" onClick={() => setOpen(false)}>About</Link><Link href="/shop" onClick={() => setOpen(false)}>Shop</Link><Link href="/blog" onClick={() => setOpen(false)}>Blog</Link><Link href="/contact" onClick={() => setOpen(false)}>Contact</Link></div>}
  </>;
}
function Footer() { return <footer className="footer"><div className="footer-top"><div><div className="footer-mark">WEARIX</div><p>A sophisticated clothing collection designed for modern, minimalist living.</p></div><div><small>Quick Links</small><Link href="/">Home</Link><Link href="/about">About</Link><Link href="/blog">Blog</Link><Link href="/shop">Shop</Link><Link href="/contact">Contact</Link></div><div><small>Get in touch</small><span>Details coming soon</span><span>Your studio address</span><span>Your email address</span></div><div><small>Subscribe to our news later</small><div className="subscribe"><input placeholder="Your email" aria-label="Your email"/><button aria-label="Subscribe"><ArrowUpRight size={16}/></button></div></div></div><div className="footer-bottom"><span>© 2026 Wearix</span><span>Built for your next collection</span></div></footer> }
function Layout({ children }: { children: React.ReactNode }) { useReveal(); return <><Header/><main>{children}</main><Footer/></>; }
function Pill({ children, href = "/shop", dark = false }: { children: React.ReactNode; href?: string; dark?: boolean }) { return <Link href={href} className={`pill ${dark ? "pill-dark" : "pill-light"}`}>{children}<ArrowUpRight size={15}/></Link>; }
function ProductCard({ product }: { product: Product }) { const [hover, setHover] = useState(false); return <Link href={`/shop/${product.slug}`} className="product-card" onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)} data-reveal><div className="product-image"><img src={hover && product.alt ? product.alt : product.image} alt={product.name}/><span className="product-tag">{product.tag}</span><span className="view-product">View piece <ArrowUpRight size={14}/></span></div><div className="product-meta"><span>{product.name}</span><span>{product.price} <del>{product.old}</del></span></div></Link>; }
function SectionTitle({ eyebrow, title, action = "/shop" }: { eyebrow: string; title: string; action?: string }) { return <div className="section-title" data-reveal><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><Pill href={action}>See all collections</Pill></div>; }
function Home() { const [heroShift, setHeroShift] = useState(0); useEffect(() => { const handle = () => setHeroShift(Math.min(window.scrollY / Math.max(window.innerHeight, 1), 1)); handle(); window.addEventListener("scroll", handle, { passive: true }); return () => window.removeEventListener("scroll", handle); }, []); const categories = [["Urban", IMG.urban], ["Latest", IMG.latest], ["Premium", IMG.premium], ["Arctic", IMG.arctic], ["Casual", IMG.casual], ["Iconic", IMG.iconic]]; return <Layout><section className="hero"><img src={IMG.hero} alt="Premium winter layers" style={{ transform: `translateY(${heroShift * 24}px) scale(${1 + heroShift * 0.025})` }}/><div className="hero-shade"/><div className="hero-content"><span className="eyebrow hero-eyebrow">Soft <i/> Warm Winter Layers</span><h1>Premium wear<br/>for modern living</h1><p>Discover our new range of soft clothes made for your daily look and your best days with the finest fabrics.</p><div className="hero-actions"><Pill>See all collections</Pill><Pill href="/contact">Contact us</Pill></div></div><div className="hero-progress"><span/><span/><span/><span/><span/><span/></div></section><section className="category-strip">{categories.map(([label, image], i) => <Link href="/shop" className={`category-card category-${i}`} key={label} data-reveal><img src={image} alt={label}/><span>{label}</span></Link>)}</section><section className="section container"><SectionTitle eyebrow="New Arrivals" title="Fresh fits in our latest drop"/><div className="product-grid">{products.slice(0,9).map(p => <ProductCard product={p} key={p.slug}/>)}</div></section><section className="story-band"><div className="story-image" data-reveal><img src={IMG.urban} alt="Modern style"/></div><div className="story-copy" data-reveal><span className="eyebrow">Wearix <i/> Since 2014</span><h2>Defining modern style</h2><p>A decade ago, we set out to redefine the modern silhouette. Today, we merge urban utility with high-end aesthetics in a resilient, beautiful collection.</p><div className="hero-actions"><Pill href="/about" dark>More about us</Pill><Pill href="/contact" dark>Contact us</Pill></div></div></section><section className="section container"><SectionTitle eyebrow="Best sellers" title="Our signature best selling pieces"/><div className="product-grid">{products.slice(9).map(p => <ProductCard product={p} key={p.slug}/>)}</div></section><Collections/><Reviews/><FeatureGrid/><BlogPreview/><ConnectBand/></Layout>; }
function Collections() { const cards = [{label:"Men's wear", title:"Premium modern collection for men", body:"Upgrade your daily look with our crafted pieces made from the finest fabrics for lasting comfort and timeless style.", price:"$45.00", image:IMG.urban}, {label:"Women's wear", title:"Modern daily wear for women", body:"Elevate your style with our signature soft pieces designed to make every single day feel truly fresh and special.", price:"$35.00", image:IMG.latest}, {label:"Children's wear", title:"Modern easy styles for children", body:"Provide your children with the best soft touch gear made for play & long lasting wear throughout every single busy day.", price:"$25.00", image:IMG.arctic}]; return <section className="collections container"><SectionTitle eyebrow="Our Collections" title="Modern collections defined by simplicity"/><div className="collection-grid">{cards.map((c,i)=><div className="collection-card" key={c.label} data-reveal><img src={c.image} alt={c.label}/><div className="collection-overlay"><span className="eyebrow">{i===2?"2026":"New"} <i/> {c.label}</span><h3>{c.title}</h3><p>{c.body}</p><div className="price-row"><span>Pricing start from:</span><strong>{c.price}</strong></div><Pill>All collections</Pill></div></div>)}</div></section> }
function Reviews() { return <section className="review-section"><div className="container review-inner" data-reveal><span className="eyebrow">Customer reviews</span><h2>The voice of quality</h2><p>Experience the difference through the words of customers who value premium fabrics and timeless design.</p><div className="review-quote">“The premium quality of the men's collection is truly unmatched lately. The fabrics feel incredibly premium and soft. This specific tailored fit is perfect for my busy office. A very sharp look. I love it every day.”</div><div className="review-meta"><span><b>James Carter</b><small>Creative Director</small></span><span className="rating"><Star fill="currentColor" size={14}/> 4.9/5 from 1k+ reviews</span></div><div className="carousel-arrows"><button><ChevronLeft/></button><button><ChevronRight/></button></div></div></section> }
function FeatureGrid() { const features = [["Everyday Comfort","Designed to feel natural on the body throughout long, active days.","All-day wear · Comfort · Relaxed fit"],["Modern Silhouettes","Contemporary shapes balance structure & ease for confident everyday styling.","Balanced fit · Modern · Structured"],["Effortless Styling","Pieces work together naturally, making daily outfit choices simple & intuitive.","Versatile · Easy to style · Layered"],["Daily Essentials","Core clothing pieces designed for frequent wear across modern everyday routines.","Core pieces · Everyday · Wearable"],["Wearable Design","Design decisions focused on comfort, fit, and real-life wearability.","Practical · Functional · Adaptable"],["Clean Aesthetic","Designed to feel natural on the body throughout long, active days.","Clean lines · Minimal · Timeless"]]; return <section className="section container feature-section"><SectionTitle eyebrow="What defines our wear" title="Where style meets ease"/><p className="feature-intro">Thoughtful design blending modern style, comfort, and versatility for everyday living across lifestyles.</p><div className="feature-grid">{features.map(([title,body,tags])=><div className="feature" data-reveal key={title}><span className="feature-number">0{iota(title)}</span><h3>{title}</h3><p>{body}</p><small>{tags}</small></div>)}</div></section> }
function iota(s:string){return (s.charCodeAt(0)%6)+1}
function BlogPreview() { return <section className="section container blog-section"><SectionTitle eyebrow="Wearix Voice" title="Elevating your daily style journey" action="/blog"/><div className="blog-grid">{blogs.map(b=><Link href={`/blog/${b.slug}`} className="blog-card" data-reveal key={b.slug}><img src={b.image} alt=""/><div><span className="eyebrow">{b.category} <i/> {b.time}</span><h3>{b.title}</h3><p>{b.excerpt}</p><small>{b.date}</small></div></Link>)}</div></section> }
function ConnectBand(){return <section className="connect-band"><div><span className="eyebrow">Stay connected</span><h2>See our community in modern silhouettes</h2><p>Connect with us on social media for a daily dose of fresh style, featuring exclusive looks from our community.</p></div><div className="hero-actions"><Pill>See collections</Pill><Pill href="/contact">Contact us</Pill></div></section>}
function PageHero({ label, title, body, image = IMG.hero }: { label:string; title:string; body:string; image?:string }) { return <section className="page-hero"><img src={image} alt=""/><div className="hero-shade"/><div className="page-hero-copy"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{body}</p></div></section> }
function About(){return <Layout><PageHero label="About" title="Timeless design, modern wearability" body="We focus on creating essential garments that remain relevant, functional, and refined across seasons." image={IMG.latest}/><section className="about-intro container"><div><span className="eyebrow">About Wearix</span><h2>More than fashion, Wearix is a commitment to intentional design.</h2></div><p>Our curated collections focus on sleek silhouettes, empowering your unique and personal journey with modern ease.</p></section><section className="stats container">{[["10M+","Pieces worn daily"],["98%","Customer Satisfaction"],["300+","Essential Styles"],["500K+","Community worldwide"]].map(([n,l])=><div data-reveal key={n}><strong>{n}</strong><span>{l}</span></div>)}</section><ConnectBand/></Layout>}
function Shop(){return <Layout><PageHero label="Shop" title="Soft layers for every day" body="Explore the full collection of crafted pieces designed for a modern, versatile wardrobe." image={IMG.urban}/><section className="section container"><div className="shop-toolbar"><span>15 pieces</span><button>All collections <ChevronRight size={15}/></button></div><div className="product-grid shop-grid">{products.map(p=><ProductCard product={p} key={p.slug}/>)}</div></section></Layout>}
function Contact(){return <Layout><PageHero label="Contact" title="Let's talk about your next collection" body="Tell us a little about what you are looking for and we will get back to you." image={IMG.premium}/><section className="contact-wrap container"><div className="contact-copy"><span className="eyebrow">Get in touch</span><h2>We would love to hear from you.</h2><p>Use this space for your future studio details, client enquiries, and support information.</p></div><form className="contact-form" onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="Your name"/></label><label>Email<input type="email" placeholder="you@example.com"/></label><label>Message<textarea placeholder="Tell us about your project" rows={5}/></label><button className="pill pill-dark" type="submit">Send enquiry <ArrowUpRight size={15}/></button></form></section></Layout>}
function Blog(){return <Layout><PageHero label="Wearix Voice" title="Elevating your daily style journey" body="Guides, ideas, and simple ways to make modern dressing feel effortless." image={IMG.latest}/><section className="section container"><div className="article-list">{blogs.map(b=><Link className="article-row" href={`/blog/${b.slug}`} key={b.slug}><img src={b.image} alt=""/><div><span className="eyebrow">{b.category} <i/> {b.time}</span><h2>{b.title}</h2><p>{b.excerpt}</p><small>{b.date}</small></div><ArrowUpRight/></Link>)}</div></section></Layout>}
function Article({ blog }: { blog: typeof blogs[number] }) { return <Layout><article className="article-page container"><span className="eyebrow">{blog.category} <i/> {blog.time}</span><h1>{blog.title}</h1><p className="article-lede">{blog.excerpt || "A considered approach to modern style, everyday comfort, and the pieces that make a wardrobe work harder."}</p><img className="article-image" src={blog.image} alt=""/><div className="article-body"><p>Modern dressing starts with intention. Choose pieces that feel effortless, hold their shape, and work naturally together across the day.</p><h2>Keep the silhouette simple</h2><p>Build around clean lines and thoughtful proportions. A relaxed layer, a considered trouser, and a soft base create a foundation that can move with you.</p><h2>Invest in everyday quality</h2><p>Fewer, better pieces make daily choices easier. Look for fabric, fit, and finish that feel as good as they look.</p></div></article></Layout>}
function ProductPage({ product }: { product: Product }) { const [image,setImage]=useState(product.image); return <Layout><section className="product-detail container"><div className="detail-gallery"><img src={image} alt={product.name}/><button onClick={()=>setImage(image===product.image&&product.alt?product.alt:product.image)} className="gallery-switch">Swap view <ArrowUpRight size={14}/></button></div><div className="detail-copy"><span className="eyebrow">{product.tag}</span><h1>{product.name}</h1><div className="detail-price">{product.price} <del>{product.old}</del></div><p>Soft, modern, and designed for daily wear. A considered essential built around comfort, clean lines, and easy styling.</p><div className="detail-line"/><div className="detail-options"><span>Size</span><div><button>XS</button><button>S</button><button>M</button><button>L</button><button>XL</button></div></div><button className="pill pill-dark full-button" onClick={(e)=>e.preventDefault()}>Add to your details later <ArrowUpRight size={15}/></button><small className="placeholder-note">Shopping is intentionally disabled until your own commerce details are connected.</small></div></section><section className="section container"><SectionTitle eyebrow="You may also like" title="More signature pieces"/><div className="product-grid">{products.filter(p=>p.slug!==product.slug).slice(0,3).map(p=><ProductCard product={p} key={p.slug}/>)}</div></section></Layout>}
function NotFound(){return <Layout><section className="not-found container"><span className="eyebrow">404</span><h1>This page is not part of the collection yet.</h1><Pill href="/">Return home</Pill></section></Layout>}
function Router(){ const [location] = useLocation(); const productSlug = location.startsWith("/shop/") ? location.slice(6) : ""; const blogSlug = location.startsWith("/blog/") ? location.slice(6) : ""; const product = useMemo(()=>products.find(p=>p.slug===productSlug),[productSlug]); const blog = useMemo(()=>blogs.find(b=>b.slug===blogSlug),[blogSlug]); return <Switch><Route path="/" component={Home}/><Route path="/about" component={About}/><Route path="/shop" component={Shop}/><Route path="/contact" component={Contact}/><Route path="/blog" component={Blog}/>{product && <Route path={`/shop/${product.slug}`}><ProductPage product={product}/></Route>}{blog && <Route path={`/blog/${blog.slug}`}><Article blog={blog}/></Route>}<Route component={NotFound}/></Switch> }
export default function App(){return <Router/>}
